C This file contains cog templates.
C Code between template and end marker is autogenerated.
C Add new forcing fields to exfflds in defs.py
C
CCOG[[[cog import cog; from defs import *]]]
CCOG[[[end]]] (checksum: d41d8cd98f00b204e9800998ecf8427e)

      useGudYearlyFields = useExfYearlyFields
      gud_chlInitBalanced = .FALSE.
      gud_chlIter0 = 0

#ifdef GUD_ALLOW_RADTRANS
      DO l = 1, nlam
       OASIM_Edfile(l) = ' '
       OASIM_Esfile(l) = ' '
       gud_inscal_OASIM(l) = 1. _d 0
      ENDDO
      OASIMstartdate1         = 0
      OASIMstartdate2         = 0
      OASIMperiod             = 0.0 _d 0
      OASIMconst              = 0.0 _d 0
      OASIM_exfremo_intercept = 0.0 _d 0
      OASIM_exfremo_slope     = 0.0 _d 0
      OASIMmask = 'c'
#endif
CCOG[[[cog
CCOGfor fld,pre in exfflds: cog.out('''
CCOG      {pre}file = ' '
CCOG      {pre}startdate1         = 0
CCOG      {pre}startdate2         = 0
CCOG      {pre}period             = 0.0 _d 0
CCOG      {pre}const              = 0.0 _d 0
CCOG      {pre}_exfremo_intercept = 0.0 _d 0
CCOG      {pre}_exfremo_slope     = 0.0 _d 0
CCOG      {pre}mask = 'c'
CCOG
CCOG      gud_inscal_{pre}    =  1. _d 0
CCOG'''.format(pre=pre, fld=fld))
CCOG]]]

      PARfile = ' '
      PARstartdate1         = 0
      PARstartdate2         = 0
      PARperiod             = 0.0 _d 0
      PARconst              = 0.0 _d 0
      PAR_exfremo_intercept = 0.0 _d 0
      PAR_exfremo_slope     = 0.0 _d 0
      PARmask = 'c'

      gud_inscal_PAR    =  1. _d 0

      ironfile = ' '
      ironstartdate1         = 0
      ironstartdate2         = 0
      ironperiod             = 0.0 _d 0
      ironconst              = 0.0 _d 0
      iron_exfremo_intercept = 0.0 _d 0
      iron_exfremo_slope     = 0.0 _d 0
      ironmask = 'c'

      gud_inscal_iron    =  1. _d 0

      icefile = ' '
      icestartdate1         = 0
      icestartdate2         = 0
      iceperiod             = 0.0 _d 0
      iceconst              = 0.0 _d 0
      ice_exfremo_intercept = 0.0 _d 0
      ice_exfremo_slope     = 0.0 _d 0
      icemask = 'c'

      gud_inscal_ice    =  1. _d 0

      windfile = ' '
      windstartdate1         = 0
      windstartdate2         = 0
      windperiod             = 0.0 _d 0
      windconst              = 0.0 _d 0
      wind_exfremo_intercept = 0.0 _d 0
      wind_exfremo_slope     = 0.0 _d 0
      windmask = 'c'

      gud_inscal_wind    =  1. _d 0

      pCO2file = ' '
      pCO2startdate1         = 0
      pCO2startdate2         = 0
      pCO2period             = 0.0 _d 0
      pCO2const              = 0.0 _d 0
      pCO2_exfremo_intercept = 0.0 _d 0
      pCO2_exfremo_slope     = 0.0 _d 0
      pCO2mask = 'c'

      gud_inscal_pCO2    =  1. _d 0
CCOG[[[end]]] (checksum: e7852dc598f08057de3a7c7ee1b656a1)

#ifdef USE_EXF_INTERPOLATION
      inp_lon0 = xgOrigin + delX(1)*exf_half
      inp_lat0 = ygOrigin + delY(1)*exf_half
      inp_dLon = delX(1)
      inp_dLat = delY(1)
# ifdef ALLOW_EXCH2
      gridNx = exch2_mydNx(1)
      gridNy = exch2_mydNy(1)
# else /* ALLOW_EXCH2 */
      gridNx = Nx
      gridNy = Ny
# endif /* ALLOW_EXCH2 */

#ifdef GUD_ALLOW_RADTRANS
      OASIM_lon0 = inp_lon0
      OASIM_lat0 = inp_lat0
      OASIM_nlon = gridNx
      OASIM_nlat = gridNy
      OASIM_lon_inc = inp_dLon
      OASIM_interpMethod  = 1
      OASIM_lat_inc(:) = inp_dLat
#endif
CCOG[[[cog
CCOGfor fld,pre in exfflds: cog.out('''
CCOG      {pre}_lon0 = inp_lon0
CCOG      {pre}_lat0 = inp_lat0
CCOG      {pre}_nlon = gridNx
CCOG      {pre}_nlat = gridNy
CCOG      {pre}_lon_inc = inp_dLon
CCOG      {pre}_interpMethod  = 1
CCOG      {pre}_lat_inc(:) = inp_dLat
CCOG'''.format(pre=pre, fld=fld))
CCOG]]]

      PAR_lon0 = inp_lon0
      PAR_lat0 = inp_lat0
      PAR_nlon = gridNx
      PAR_nlat = gridNy
      PAR_lon_inc = inp_dLon
      PAR_interpMethod  = 1
      PAR_lat_inc(:) = inp_dLat

      iron_lon0 = inp_lon0
      iron_lat0 = inp_lat0
      iron_nlon = gridNx
      iron_nlat = gridNy
      iron_lon_inc = inp_dLon
      iron_interpMethod  = 1
      iron_lat_inc(:) = inp_dLat

      ice_lon0 = inp_lon0
      ice_lat0 = inp_lat0
      ice_nlon = gridNx
      ice_nlat = gridNy
      ice_lon_inc = inp_dLon
      ice_interpMethod  = 1
      ice_lat_inc(:) = inp_dLat

      wind_lon0 = inp_lon0
      wind_lat0 = inp_lat0
      wind_nlon = gridNx
      wind_nlat = gridNy
      wind_lon_inc = inp_dLon
      wind_interpMethod  = 1
      wind_lat_inc(:) = inp_dLat

      pCO2_lon0 = inp_lon0
      pCO2_lat0 = inp_lat0
      pCO2_nlon = gridNx
      pCO2_nlat = gridNy
      pCO2_lon_inc = inp_dLon
      pCO2_interpMethod  = 1
      pCO2_lat_inc(:) = inp_dLat
CCOG[[[end]]] (checksum: 2978b780521f5fda098be9a3e78ade77)
#endif /* USE_EXF_INTERPOLATION */
